FROM nginx:alpine

# Install OpenSSL and dos2unix to handle potential line ending issues
RUN apk add --no-cache openssl dos2unix

# Copy the certificate generation script
COPY scripts/generate_self_signed_cert.sh /usr/local/bin/generate_self_signed_cert.sh

# Run dos2unix to ensure the script has LF line endings, and make it executable
RUN dos2unix /usr/local/bin/generate_self_signed_cert.sh && \
    chmod +x /usr/local/bin/generate_self_signed_cert.sh && \
    sh -x /usr/local/bin/generate_self_signed_cert.sh

# Copy the Nginx configuration
COPY data/nginx.conf /etc/nginx/nginx.conf

# Expose necessary ports
EXPOSE 80 443

# Start Nginx
CMD ["nginx", "-g", "daemon off;"]
